name: Playwright Test Automation CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci
        working-directory: ./MyProjects

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./MyProjects

      - name: Run only dummy test
        run: npx playwright test tests/dummyTest.spec.js
        working-directory: ./MyProjects

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: MyProjects/playwright-report # Updated path to match actual folder
